# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-26 21:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'color',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Estado',
                'db_table': 'estado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistorialGlobo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 26, 16, 19, 32, 327118))),
                ('fecha_inicio', models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 26, 16, 19, 32, 327173))),
                ('fecha_fin', models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 26, 16, 19, 32, 327212))),
                ('estado', models.ForeignKey(blank=True, db_column='estado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Estado')),
            ],
            options={
                'verbose_name': 'Historial Globo',
                'db_table': 'historial_globo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'local',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'modelo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha', models.CharField(blank=True, max_length=1000, null=True)),
                ('color', models.ForeignKey(blank=True, db_column='color', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Color')),
                ('local', models.ForeignKey(blank=True, db_column='local', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Local')),
                ('modelo', models.ForeignKey(blank=True, db_column='modelo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Modelo')),
            ],
            options={
                'db_table': 'movimiento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'talla',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Usuario',
                'db_table': 'globo',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='movimiento',
            name='proveedor',
            field=models.ForeignKey(blank=True, db_column='proveedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Proveedor'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='talla',
            field=models.ForeignKey(blank=True, db_column='talla', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Talla'),
        ),
        migrations.AddField(
            model_name='historialglobo',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Usuarios'),
        ),
    ]
