# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-26 21:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialglobo',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 26, 16, 19, 37, 707005)),
        ),
        migrations.AlterField(
            model_name='historialglobo',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 26, 16, 19, 37, 707100)),
        ),
        migrations.AlterField(
            model_name='historialglobo',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 26, 16, 19, 37, 707061)),
        ),
    ]
