# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-26 21:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181026_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='local',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='destino',
            field=models.ForeignKey(blank=True, db_column='destino', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='destino', to='app.Local'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='origen',
            field=models.ForeignKey(blank=True, db_column='origen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='origen', to='app.Local'),
        ),
        migrations.AlterField(
            model_name='historialglobo',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 26, 16, 38, 0, 698713)),
        ),
        migrations.AlterField(
            model_name='historialglobo',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 26, 16, 38, 0, 698864)),
        ),
        migrations.AlterField(
            model_name='historialglobo',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 26, 16, 38, 0, 698771)),
        ),
    ]
